name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: test_db
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Check MySQL status
        run: docker exec $(docker ps -q -f name=mysql) mysqladmin ping -h 127.0.0.1 -u test -ptest

      - name: Run e2e tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: test
          DB_PASS: test
          DB_NAME: test_db
        run: npm run test:e2e

      - name: Build
        run: npm run build